export {default as LoginScreen} from "./Login"
export {default as CadastrarScreen} from "./Cadastrar"
export {default as PerfilScreen} from "./Perfil"
export {default as HomeScreen} from "./Home"
export {default as MapScreen} from "./Map"
export {default as TestScreen} from "./Test"
export {default as SurpriseScreen} from "./Surprise"
export {default as CameraScreen} from "./Cameras"
export {default as ArquivoScreen} from "./Arquivo"
export {default as EnviarMensagemScreen} from "./EnviarMensagem"
export {default as ChatScreen} from "./Chat"
export {default as QrCodeScreen} from "./QrCode"
export {default as VideoAudioScreen} from "./VideoAudio"
export { default as SairScreen} from "./Sair"