export {default as LoginScreen} from "./Login"
export {default as CadastrarScreen} from "./Cadastrar"
export {default as PerfilScreen} from "./Perfil"
export {default as HomeScreen} from "./Home"
export {default as MapScreen} from "./Map"
export {default as TestScreen} from "./Test"
export {default as SurpriseScreen} from "./Surprise"